version: "3.9"

services:
  django_app:
    container_name: django_app
    build: .
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    command: sh -c "python manage.py collectstatic --no-input && gunicorn --bind=0.0.0.0:8000 config.wsgi:application"
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/app/staticfiles
    restart: on-failure
    depends_on:
      - django_app
  db:
    restart: always
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file: .env
volumes:
  app_volume:
  static_volume:
  postgres_data:
